language: python

python:
  - 2.7

services:
  - docker

install:
  - pip install -U codecov

script:
  - bash test-container.sh

after_success:
  - codecov

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  skip_existing: true
  user: papaemmelab
  password: <TO REPLACE THIS RUN `travis encrypt --add deploy.password`>
  on:
    tags: true
    repo: papaemmelab/toil_cnacs
    python: 2.7
    branch: master
